batch_size: 1
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 500
log_loss_every_n_steps: 10
save_checkpoint_every_n_steps: 500
weight_decay: 10e-6
lr: 1e-4
hyperbolic: True
beta: 5
augment: False
mask_nms: True
desc: "test"

model:
  out_dim: 2
  base_model: "resnet101"
  freeze_base: True

loss:
  temperature: 0.5
  use_cosine_similarity: True
  margin: 0.5
  mask_loss: False
  object_loss: True
  include_hierarchical: True
  type: "triplet"


