batch_size: 1
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 100
log_loss_every_n_steps: 10
save_checkpoint_every_n_steps: 2000
weight_decay: 10e-6
fp16_precision: False
hyperbolic: False
contrastive_loss_weight: 5

model:
  out_dim: 64
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 0
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
  type: "nce"


